# Generated by Django 4.0.3 on 2022-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_hoteldetails_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=200)),
                ('foodBoxes', models.PositiveIntegerField(default=0)),
                ('food', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
    ]
