# Generated by Django 4.0.3 on 2022-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFoodRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('alphaString', models.CharField(max_length=20)),
            ],
        ),
    ]
