# Generated by Django 4.0.3 on 2022-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_userfoodregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='availableStatus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfoodregistration',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
