# Generated by Django 4.0.3 on 2022-03-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooddetails_availablestatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetails',
            old_name='fb_profile',
            new_name='Type',
        ),
    ]
