# Generated by Django 4.0.3 on 2022-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_fb_profile_hoteldetails_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetails',
            old_name='Type',
            new_name='star',
        ),
    ]
